services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: sossego_pet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: sossego_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sossego_pet_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:
    image: nginx:alpine
    container_name: sossego-front
    volumes:
      - ./nginx:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - app