services:
  db:
    image: postgres:18
    container_name: sossego-db
    restart: always
    environment:
      POSTGRES_DB: sossego_pet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - sossego-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: sossego-app
    restart: always
    depends_on:
      db:
        condition: service_healthy   # espera o banco estar pronto de verdade
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sossego_pet_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    networks:
      - sossego-net

  frontend:
    image: nginx:alpine
    container_name: sossego-front
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - sossego-net

networks:
  sossego-net:
    driver: bridge

volumes:
  postgres_data:
